### PR TITLE
Add storage bucket info. Drive-by de-linting of consulted files.

### PR DESCRIPTION
**Pull request by jsoules**
This is left as a draft for right now, because I had a couple open queries about the exact mechanics of reading from cloud storage--it seems obvious, since we have SHA1 URIs for the files, but I'd feel most comfortable if I could give a concrete example of what an access URI for a Google storage bucket looks like.

Additional queries:

* So a requesting client is supposed to be able to get the stored data out of the bucket just from knowing the URI, first, before it makes any requests. That makes sense except for the file potentially being split into pages--does the URI of the base file actually contain the manifest, with the SHA1s of the different chunks?
* Is there any sort of access restrictions for download? Or would leaking a Google download URI compromise files in the bucket? (If a SHA1 for a file is revealed, there's at least a chance that the data won't be in the cache when a non-authorized party tries to fetch it...)
* ...am I going way too far on the background thing?

### CODE REVIEW

**Comment by magland** [comment]
> This is left as a draft for right now, because I had a couple open queries about the exact mechanics of reading from cloud storage--it seems obvious, since we have SHA1 URIs for the files, but I'd feel most comfortable if I could give a concrete example of what an access URI for a Google storage bucket looks like.

Do you mean like this? `https://storage.googleapis.com/storage/v1/<bucket-name>/<object-name>` (see https://cloud.google.com/storage/docs/request-endpoints)

In our case, `<object-name>` would be `sha1/xx/xx/xx/xxxxxxxxxx....`

> 
> Additional queries:
> 
> * So a requesting client is supposed to be able to get the stored data out of the bucket just from knowing the URI, first, before it makes any requests. That makes sense except for the file potentially being split into pages--does the URI of the base file actually contain the manifest, with the SHA1s of the different chunks?

The Python client doesn't query the bucket directly. The client first checks local storage. If not there, it requests from the daemon. The daemon then checks the buckets for the channels it belongs to. If not found in buckets, the daemon requests via kachery channels (pub-sub request). If the file then is uploaded to a bucket by a remote node, then the daemon will retrieve the file from the bucket. After downloading from bucket, the daemon stores locally, and responds to the Python client. The Python client can now read from the local file.

> * Is there any sort of access restrictions for download? Or would leaking a Google download URI compromise files in the bucket? (If a SHA1 for a file is revealed, there's at least a chance that the data won't be in the cache when a non-authorized party tries to fetch it...)

Right now there is intentionally no access restrictions for download ... except you must know the hash of the file to be able to get it -- and it is not possible to list bucket contents.

> * ...am I going way too far on the background thing?

It's a really nice write-up! It almost belongs as a standalone article. As long as it stays in a separate file, I think it's fine.

**Comment by jsoules** [comment]
> The Python client doesn't query the bucket directly. [...]

Sorry, I phrased that poorly--I meant a requesting node. The *daemon* knows the URI for the whole file, but the file is actually represented as a bunch of pages, which the daemon doesn't know just from the fingerprint of the complete file--I'm assuming the requesting daemon gets ahold of the manifest somehow?

> Right now there is intentionally no access restrictions for download ... except you must know the hash of the file to be able to get it -- and it is not possible to list bucket contents.

Okay. I think we should probably stress this more on the security page--that it's essential to guard the SHA1 addresses tightly even if request permission on the channel is limited. If the SHA1 is leaked, reconstructing the bucket's download URI would be pretty straightforward.

**Comment by magland** [comment]
> The _daemon_ knows the URI for the whole file, but the file is actually represented as a bunch of pages, which the daemon doesn't know just from the fingerprint of the complete file--I'm assuming the requesting daemon gets ahold of the manifest somehow?

When a node needs to request a large file with a manifest, it first requests the manifest from the channel. If it manages to load that, then it can start requesting the chunks/pages for the large file from the channel as well. Actually, only the chunks go up to the bucket, so the largest single object on the bucket should only be 20 MiB.

**Comment by magland** [comment]
Can I go ahead and merge this, even though it is wip?

**Comment by jsoules** [comment]
Yeah, I think this is more or less set now. If we realize we need to edit it later, we can do so easily enough.

**Pull request merged**
